process.env.PORT='3000'
process.env.S3_URI='http://minioadmin:minioadmin@localhost:9000'
process.env.S3_BUCKET='file-transfer'
process.env.S3_PREFIX='NON-PROD/'
process.env.LOCAL_STORAGE_DIR='DEST1'
process.env.CRA_PUB_CERT_PATH='path/to/cert.pem'
process.env.CRA_PRIVATE_KEY_PATH='path/to/private-key.pem'
